### ISSUE TITLE
Is it working end to end for buisiness already?

### ISSUE THREAD

**Issue by jdees** [derrix060/onedriveClient#1]
Or is it still in development to make it work?

Useful to put this in for documentation?

Thanks,
J

**Comment by derrix060** [comment]
It's not working yet. I'm very busy doing some jobs, but I hope next month I can be free to finish this issue

**Comment by derrix060** [comment]
I'm testing here with my account and it is working so far, @jdee, if you could test and report any problem, I would appreciate it!

**Comment by threepistons** [comment]
Given: that I have just installed from Git according to the readme and I have Python as follows:
```
me@machine:~$ python3 -V
Python 3.5.3
me@machine:~$ python -V
Python 2.7.13
```
And my site uses ADFS to handle logins, and I ran dbus and gnome-keyring as you said, and I am using MATE on Ubuntu 17.04.

When I try to: add my account using onedrived-pref
I expect: my account to be saved
I get: the following
```
me@machine:~$ onedrived-pref account add -b
Gkr-Message: secret service operation failed: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/home/me/.config/onedrived/onedrived_config_v2.json'. Use default.
NOTE: To better manage your OneDrive accounts, onedrived needs permission to access your account info (e.g., email address to distinguish different accounts) and read/write your OneDrive files.

Paste this URL into your browser to sign in and authorize onedrived:

https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fod.cnbeining.com&client_id=6fdb55b4-c905-4612-bd23-306c3918217c

The authentication web page will finish with a blank page whose URL starts with "https://od.cnbeining.com". Paste this URL after the prompt.
Paste URL here: https://od.cnbeining.com/?code=AQABAAIAAAABlDrqfEFlSaui6xnRjX5EsUHwpqJxqLo8YtcqSqG2qggw8UkulURvrHJQ_JdBC3-M-W6eyOQO7I4aqn-aJUzw0cM4cVew7Gy2tgacPichSLWv2DUN9UnvH8ebC7D9wx0qw0clBdjj3OExJNKwQI8J1LaMtaTtZeP_k5dY3bqYyWBaMkPUCoglyzY5AxnPhfUpXb0x75tFw5HI7cD4Rb3uMRGAR2nW6kVL8fsjrGGOcn1vvYOPE-Ow5A9ko39BOjkGzeppXYeMD9k6TE7eoXqrQlayaBisEn5PcbCm0Pa4FWg13_GX2iX8G4CurBopPHyzhUdVdSOga3l0mlDbgMwLq3ZSA38jeDN7y7f-Vr04p5jcCpPVHfa6bbC8zGb9XaXT_zfaDNK5LTYYt15cMnDPbm8xKjjeiLnhana3xyS9LAVMbq2xQoha-AeMNAn6kt4wy95i_lSvOwyi6iCLrePFcYK3AhQL5QbslpWfWvcy9Pxo9YeGlOLcl9wdS2bhST1fpIQUxQgwlzAGeVOvxIslR1UIxmfhlvcZOnVJe3xebN3I5D-1EJskGbSNhy5gIUF-zO82NT29ZVL3ANBJynAxrvDoJafh6bz55A8Bk_4uqEbAEIWbepIxtQQgzUO8rxt_UH_jQoiIclJ1UvuRWnT2q7aMH2QFB0K0ByHp07Uv5yAA&session_state=e912153e-5ffb-4581-9847-3c775a00e7bb
Athenticating...
Refreshing token...
Updating client
Authenticated!
Successfully authorized onedrived.
Need authenticate again to get personal information
Paste this URL into your browser to sign in and authorize onedrived:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=0e170d2c-0ac5-4a4f-9099-c6bb0fb52d0c&response_type=code&redirect_uri=https%3A%2F%2Fonedrivesite.mario-apra.tk%2F&scope=User.Read

The authentication web page will finish with a blank page whose URL starts with "https://onedrivesite.mario-apra.tk/". Paste this URL after the prompt.
Paste URL here: https://onedrivesite.mario-apra.tk/?code=OAQABAAIAAAABlDrqfEFlSaui6xnRjX5E6uaVvnqZ4pywuKkesTQTNszG6m7YG5mtYShpUqjSQqXqjkqdveT8sZXB9VSu27pbvc4YTSzn4AyD_MCS6_8pcIF39YxtTgFqcWJpgyOHctjGTSW7iH8mdukbNCyLH-XopxFy97x1tkO8rynv2hVBahtZGlPy9Z8lK7lLcarjR33lzp5dZxAdJaaH6K4l2n79MMXVW7TzuNwEdk8QBg8ZCu9r2vVnbhdF5BC9pROod56CDeBV1OPXQgkkKKZD-gLyswgE6vamVUXcMHa3gZPHrByYCW2ipVvL0KdZTBkwXNGlgbV-4UzjHf74DLImS2eOHxNYnb9Jy23MKNv-JnBs-UrVKmUDBLecIIELma1_9Ne9D3XbF26GOIxDUInsLMoSeJ7OEY4s2rRIYKGcXHTZrWhnEEviYReZ_wWtBgdv3a7UxFP471Ky7cu7zwWWMqOLy9mODBQRl8EaFfx5DwR9Xg0COOKyYTa3auonGXkI6cgXRcszVrgH25k40Kx05gmf8tz8TN1DEyEgqaSIaP7whURJGTXlJKE-7hCuJOPpm7oKyX36ybZLSuTVD5r1XRCJ4LQMGucF39GzZen5rvZSy_CiRDgANud8-kWMciArKghUDfzzJqz1StybHiBAbyz6M3u8zWZJFWhEn-AZ_GTSxjXxYreKDnyH4fe9MF6TCLCtC-dZiCmwkKBiWPaUVQdes7A3-01VZS8hU2ByT3LzeCAA&session_state=e912153e-5ffb-4581-9847-3c775a00e7bb

Failed to save account: 'refresh_token'.
```

**Comment by derrix060** [comment]
Hello @threepistons, thanks for the feedback. I've never heard about ADFS before. I will try to search it in the "uggly" manual provided by Microsoft, and I will return.

**Comment by Angeall** [comment]
Hello @derrix060 ! I'm having the same bug as @threepistons, the first authentication works, but not the second (or at least, the account can't be saved, as the error message could tell : Failed to save account: 'refresh_token').

Do you have some leads so far ?

**Comment by derrix060** [comment]
Hmm, I remember that I had to to some changes on the keyring, because I was using the xybu/onedrived-dev  before. I will search about and just tell you guys.

**Comment by Angeall** [comment]
Have you had the time to investigate the problem ? :smile:

**Comment by derrix060** [comment]
Not yet, sorry. I've moved to New Zealand and I'm looking for a work yet ;)

**Comment by c0ki** [comment]
I have the same bug (first authentication OK, second ERROR: Failed to save account: 'refresh_token').
I try to use --code option, but this option bypass only first authentication, second always need url and failed.

I try to use https://developer.microsoft.com/en-us/graph/graph-explorer and no problem to create folder.

**Comment by derrix060** [comment]
Thank you @c0ki, I think that I need to refactor and use the graph-explorer. In the case to the second authentication I will work on this.

**Comment by derrix060** [comment]
Guys, I've download the Ubuntu from zero, installed on virtual box, install python, pip, everything from zero, and everything goes well. I think that the error could be the adm from your accounts, that doesn't allow some configuration. But if you can use the graph-explorer (this is the new way from the Microsoft, and the only supported now), I have to refactor and start to use this. If someone want to help me, please let me know.
