### ISSUE TITLE
Failed to save account: 'access_token'

### ISSUE THREAD

**Issue by pat-s** [derrix060/onedriveClient#13]
After solving #7 I get the following when adding a business account:

```
Athenticating...
Refreshing token...
Updating client
Authenticated!
Successfully authorized onedrived.
Failed to save account: 'access_token'.
```

Also note the typo in "athenticating".

Would love to get this working! Thanks for your work @derrix060

**Comment by derrix060** [comment]
Can you provide more information to how to replicate this issue? And if is possible, use the debug tag.

**Comment by tigerjack** [comment]
Hi @derrix060, same issue here when I try to run `onedrived-pref account add -b`.
Just after copy-pasting the url inside the terminal for the second time, it simply returns 

``
Successfully authorized onedrived.
Failed to save account: 'access_token'.
``

Also, at the very beginning, it shows the following warning:

``
WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/home/myusername/.config/onedrived/onedrived_config_v2.json'. Use default.
``
