### ISSUE TITLE
onedrive for bussiness authentification failes

### ISSUE THREAD

**Issue by marian-code** [derrix060/onedriveClient#14]
Hi,
I have a problem with authentication of onedrive for business. In the two step process the first is ok but on the second step when I paste the url I get error message: Failed to authorize onedrived: name 'log' is not defined. (see in file auth). I also tried to install manually and the included test fails for me see output in file test

[auth.txt](https://github.com/derrix060/onedriveClient/files/1863388/auth.txt)
[test.txt](https://github.com/derrix060/onedriveClient/files/1863389/test.txt)

**Comment by Daryolo** [comment]
I'm getting the same error :(

**Comment by ezatterin** [comment]
+1 with the same error.

**Comment by derrix060** [comment]
I will look at that tomorrow. Today I'm doing the [google code jam](codejam.withgoogle.com/2018/challenges/00000000000000cb/dashboard)

**Comment by derrix060** [comment]
I've pushed some code, can you check it again? This was a very basic issue, I apologize for that.

**Comment by Daryolo** [comment]
Works well for me now, thanks for fixing 👍

**Comment by ezatterin** [comment]
Works for me too, thanks a lot!
