### ISSUE TITLE
Failure to add business account

### ISSUE THREAD

**Issue by bomberb17** [derrix060/onedriveClient#3]
I am running
`onedrived-pref account add -b`
but after pasting the second link, I'm getting the error:
`Failed to save account: 'refresh_token'.`
Tried twice but can't get past this

**Comment by Angeall** [comment]
Duplicate (although with a better title) of #1 @derrix060 is working on it.

**Comment by derrix060** [comment]
@Angeall do you mean [Duplicati](https://www.duplicati.com/)?? If so, unfortunately the propose is a quite different. The Duplicati only do the backup, is not like this project, that is a sync between the server and the client...
