### ISSUE TITLE
Remove f-strings or import it from future

### ISSUE THREAD

**Issue by derrix060** [derrix060/onedriveClient#47]
F-strings were introduced on python 3.6 but this project is compatible with python 3.4 +.

Rather remove all f-strings and manually replace it, or use [this project](https://github.com/asottile/future-fstrings)

**Comment by Modelmat** [comment]
Whilst I believe f-strings are much better and cleaner than the `.format` style, the future-fstrings project seems a little dodgy and (not that I have seen any) likely to break. I think we should use that project's cli script to generate `.format` style files and continue to use them.

**Comment by sameshl** [comment]
@derrix060 I would like to work on this. So if I understand correctly, I am supposed to remove all f-strings and manually replace it with `.format` style?

**Comment by Modelmat** [comment]
You could manually replace it or using the future-fstrings project's CLI tool for converting f-strings to format-strings and then replace the updated files.

So, yes.

**Comment by sameshl** [comment]
I tried grepping but couldn't figure out a way for manually finding all the f-strings. can you help me out @Modelmat

**Comment by Modelmat** [comment]
Take a look at https://github.com/asottile/future-fstrings#showing-transformed-source

**Comment by derrix060** [comment]
Sorry for the delay, I was on holidays.  Yes, the idea is changing the f-strings (`f'... {var} ...'`) to `.format` style (`'... {} ...'.format(var)`)

**Comment by grvkmrpandit** [comment]
use import from future to make it compatible with python 3.6

**Comment by derrix060** [comment]
@RobatBender you're right, someone might have done it already.
