### ISSUE TITLE
Testing: Successfull! 

### ISSUE THREAD

**Issue by Reepun** [derrix060/onedriveClient#6]
Hello! I've tested the current release on my Onedrive for Business and it works without any issues after getting all the dependencies figured out for CentOS. 
Further, I'm curious about what's been previously discussed, which is getting it authenticated under our own domain. Where and how would I go about changing the program to use our own domain for authentication, so it doesn't have to pass through yours? 
I'm available to help with testing and have full administrative access to Microsoft 365. 
Thanks for the help and good software.
Fredrik

**Comment by derrix060** [comment]
Hello @Reepun , thank you for the feedback!!

About the dependencies for the CentOS, can you describe with more detail, and them I put this on README??

About be authenticated under your own domain, I will refactor some pieces of code and I will expose the client ID, Secret and Redirect in a .yml file, you will just need to replaces the configurations there.

About the testing, you said that you have full administrative access to 365, can you create a test account, with only permissions to onedrive, and with less than 1MB, and them I will create some tests. This account will be exposed here in Github, if you don't feel comfortable with this, you don't need to create the account ;) 

Derrix

**Comment by derrix060** [comment]
Hello again @Reepun,

I've created the [config file](https://github.com/derrix060/onedriveClient/blob/master/onedrive_config.yml) and now you can use your own client ID, and secret without any problem.

I will create one tutorial how to create the accounts and the permissions that you need and will put on README file.

Derrix
