### ISSUE TITLE
Delete from OneDrive - remains

### ISSUE THREAD

**Issue by Daryolo** [derrix060/onedriveClient#8]
Hello guys.

I'm working on a project with onedrive and trying to link the Onedrive with a Scanner, by installing it on a raspberrypi. What's wrong now, is that when I delete a file on onedrive, it still remains on the raspi. And when I scan the next file - the "deleted" file pops up again in my OneDrive account. If I'm not wrong, this worked like a charm before. I can't see the reason why it doesn't delete it from the raspi.

Some help would be much approved.

Thanks!

**Comment by derrix060** [comment]
It should sync automatically. I will test it.

**Comment by Daryolo** [comment]
Hello derrix,
thanks for your answer. I'm somehow not able to test it. I'm now getting some error when trying to add an account. 
For business Account: Failed to authorize onedrived: name 'log' is not defined.
For regular Account: Failed to save account: Failed to create the collection: Prompt dismissed...

I can't really see how it's not working, I'm doing everything as back then, when it worked.

**Comment by derrix060** [comment]
Okay, I will try to take a look at this next week. Can you try to run in debug mode `--debug` and put here more detailed? Don't forget to omit the sensitive data.

**Comment by Daryolo** [comment]
I'm not able to do this until next week, I'm sorry! Gonna do so if you need next week.

**Comment by Daryolo** [comment]
Hello derix

Still having the same error. It remains, unless I restart onedrive or I upload a new file. The other way it's working, when I delete it on the raspberry-pi it instantly removes it from the onedrive website client.

**Comment by derrix060** [comment]
It will remain until the next `scan`. It is defined in your configuration file (onedrived_config_v2.json) and the default is 6 hours.

If you need to change for some reason, change the `scan_interval_sec` to another value.
